### PR TITLE
Reject reqs missing x-hub-signature header if secret_token defined

### LINKED ISSUE #16: drop_invalid contains security issue if no header x-hub-signature
I found a security issue with the plugin. If the header "x-hub-signature" isn't in the request and drop_invalid is setted to "true" then the message isn't dropped...

Version: latest

Operating System: MACOS

Config File :
input {
github {
drop_invalid => true
ip => "0.0.0.0"
port => "8080"
secret_token => "test"
}
}

Steps to Reproduce:
run
curl -XPOST -d'test' localhost:8080
The request won't be dropped by the plugin because the header "x-hub-signature" isn't present, so it pass the control...

### PR DESCRIPTION
**Pull request by mindbat**
Should fix #16 

Updates `verify_signature` to check for the absence of the `x-hub-signature` header when `secret_token` is defined, and treats such requests as invalid.

Also revises an existing test to match the new behavior, and adds three more tests to verify that we don't overcorrect by requiring (or checking) the header if `secret_token` is _not_ defined.

### CODE REVIEW

**Comment by yaauie** [comment]
The PR looks like it works _as-advertised_, but I'd appreciate a little validation on my understanding of how it's supposed to work to determine whether this should be considered a breaking change or a fix to the current implementation.

From what I understand, this input sets up an HTTP web server, listening for requests, and the Github hooks API includes a signature of each raw request body as a `x-hub-signature` header, which we capture onto the created event. If this input is started with a `secret_token` directive, we use it along with the raw body to validate against the event's `x-hub-signature`, so the absence of an appropriate header indicates that we cannot ensure that the event stemmed from an authorised web hook.

This PR, then, includes the absence of the header along-side a `secret_token` as an indicator that the event is invalid, allowing further filtering like `drop_invalid` to work as expected when the HTTP endpoint receives payloads that are not from github.

If this is the case, then I would consider the PR to be a fix for the current implementation, in which case a patch-level bump as proposed is appropriate.

**Comment by mindbat** [comment]
> This PR, then, includes the absence of the header along-side a secret_token as an indicator that the event is invalid, allowing further filtering like drop_invalid to work as expected when the HTTP endpoint receives payloads that are not from github.

@yaauie Exactly. No header means we _can't_ validate, so we consider it invalid, and let `drop_invalid` take it from there.

> I would consider the PR to be a fix for the current implementation

Yep, that's what's intended here. Not a breaking change, just a patch to bring the behavior in-line with expectations.

File: lib/logstash/inputs/github.rb [hunk 1]
```diff
@@ -72,6 +72,9 @@ def verify_signature(event,body)
         event.tag("_Invalid_Github_Message")
         is_valid = false
       end
+    elsif @secret_token && !sign_header
```
Comment (yaauie) [inline lib/logstash/inputs/github.rb]: While your change is functionally correct and minimal, there are a couple of anti-patterns within the existing method definition (e.g., `if not`, unnecessary `is_valid` variable) and with this change the reasoning behind this code becomes a little less clear, a little harder to follow, and a little more repetitive.

I'd prefer a functionally-equivalent refactor to this whole method, which I think is an improvement:

~~~ ruby
  def verify_signature(event,body)
    # skip validation if we have no secret token
    return true unless @secret_token

    sign_header = event.get("[headers][x-hub-signature]")
    if sign_header
      hash = 'sha1=' + OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha1'), @secret_token, body)
      event.set("hash", hash)
      return true if Rack::Utils.secure_compare(hash, sign_header)
    end

    event.tag("_Invalid_Github_Message")
    return false
  end
~~~

Comment (mindbat) [reply lib/logstash/inputs/github.rb]: Makes sense to me! 7d54a10

**Comment by mindbat** [comment]
@yaauie Does everything look good now? Are there additional changes you'd like to see?

**Comment by ngapaillard** [comment]
Hi !
Thanks for fixing ! (A little late I know)
